# Generated by Django 5.0.4 on 2025-04-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
