# Generated by Django 5.0.4 on 2025-02-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MODERATOR', 'MODERATOR'), ('COMMON', 'COMMON')], default='COMMON', max_length=30),
        ),
    ]
