# Generated by Django 5.1.3 on 2024-12-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
