# Generated by Django 5.1.3 on 2024-12-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 12, 16, 38, 7, 238016, tzinfo=datetime.timezone.utc)),
        ),
    ]
