# Generated by Django 5.1.3 on 2024-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_emailverificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
