# Generated by Django 5.1.3 on 2024-12-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
