# Generated by Django 5.1.3 on 2025-01-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
