# Generated by Django 5.1.3 on 2025-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='step',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 2), (3, 3)], null=True),
        ),
    ]
